### ISSUE TITLE
Get-Packageprovider triggers a Pending File Rename Operation

### ISSUE THREAD

**Issue by tehsuk** [OneGet/oneget#179] opened 2016-04-21 20:59 UTC
OS: Server 2008 R2 & Server 2012 R2
PSH/WMF: 5.0
Bug:

If I run Get-Packageprovider, a Pending File Rename operation is triggered which causes a pending reboot.

Steps to reproduce:
1. Install WMF 5 RTM on Windows Server 2008 R2 or Server 2012 R2
2. Open Powershell
3. Verify the output of (get-itemproperty "hklm:\system\currentcontrolset\control\session manager").PendingFileRenameOperations is blank
4. Run Get-PackageProvider

Result:
- The output of  (get-itemproperty "hklm:\system\currentcontrolset\control\session manager").PendingFileRenameOperations returns $env:temp\Microsoft.PackageManagement\$anumber

This wrecks havoc with automation that checks for pending reboots.

Edit:  Get-PSRepository does the same thing.
Edit 2: Verified the same behavior on Windows 2012 R2

**Comment by quoctruong** [comment] 2016-04-28 21:52
Thanks for reporting the issue @tehsuk, we will look into this bug.

**Comment by jianyunt** [comment] 2016-06-07 17:59
Thanks for reporting it. The fix will be in released soon.

**Comment by tylergohl** [comment] 2016-06-18 19:44
@jianyunt - do we have an estimate on soon?  Is that a month, 3 months.. 6 months?  We've had to write some pretty unfortunate hacks to deal with this bug that we'd love to get rid of :)

**Comment by jianyunt** [comment] 2016-06-20 18:58
@tylergohl, the fix is in OneGet code which is a Windows Component. It will be released in the next  Windows release.  However we can publish the source code (I will do it this week), which allow you compile the OneGet binaries to try it out.  Sorry for the inconvenience.

**Comment by mitchmeade** [comment] 2016-06-27 17:41
I can confirm that this problem is also happening with Get-PackageSource and Register-PackageSource on Windows Server 2012 R2.  I wrote a PS profile that verifies that each PS session has Package source defined for our PS Module repository and our chocolatey repository.  I didn’t cache this until it was pushed to production and is causing issues with automation.  Can you elaborate on “next Windows release”, do you mean the next OneGet package manager release for Windows or do you truly mean that this fix will not be available until a major version of Windows is released?

**Comment by jianyunt** [comment] 2016-06-27 18:11
@mitchmeade, @tylergohl Sorry for the inconvenience.There are a few options:
1. [OneGet source code](http://oneget.org) with the bug fix got updated. If you are blocked right now you may git clone the code, build it via MSbuild or Visual Studio and try it out now.
2. Wait for our next WMF 5.1. Sorry I cannot tell you the exact date, but hope it's soon.
3. We had the Windows Technical Preview 5 release in May, I mean the next release mentioned above is one after TP5.

**Comment by mitchmeade** [comment] 2016-06-27 18:20
@jianyunt,  I noticed that the package source registration for chocolatey is machine based but the package source for the PS Module repository is user based, i.e. C:\Users\DTest1.2V5\AppData\Local\Microsoft\Windows\PowerShell\PowerShellGet\PSRepositories.xml.

Is there a way that I can register the package source for PS module repositories globally to reduce the occurrence of this issue?

**Comment by bmanikm** [comment] 2016-06-27 19:54
@mitchmeade, Yes, PS module repositories are user based. It is not possible to register the PSRepositories for all users. You may consider copying the already created PSRepositories.xml to the user specific path %localappdata%\Microsoft\Windows\PowerShell\PowerShellGet\ .

**Comment by mitchmeade** [comment] 2016-06-27 19:58
@bmanikm, @jianyunt 

That is the exact workaround I was considering, thanks for the confirmation.

Mitch

**Comment by jianyunt** [comment] 2016-08-15 22:23
The file pending reboot issue is fixed in [WMF 5.1](https://blogs.msdn.microsoft.com/powershell/2016/07/16/announcing-windows-management-framework-wmf-5-1-preview/).

**Comment by mitchmeade** [comment] 2016-08-17 14:33
Thanks for the heads up….  We have a workable solution at the moment so we’ll wait until this package makes it to RTM but in the meantime, I will do some limited deployments.


Mitch Meade
System Architect II

[cid:image001.jpg@01D1A6C1.19BAB360]

email Mitch.Meade@CloudJumper.com<mailto:Mitch.Meade@CloudJumper.com>
phone 844.645.6789
direct 916.389.2822
web www.CloudJumper.com<http://www.cloudjumper.com/>
twitter @CloudJumperWaaS<https://twitter.com/nGenxCloud>

[cid:image002.jpg@01D1A6C1.19BAB360]

**Comment by jianyunt** [comment] 2016-11-03 22:44
Thanks for reporting the issue. The fix made in WMF 5.1 Preview, Win10 Anniversary, and Windows Server 2016.

**Comment by jsco2t** [comment] 2016-11-04 13:43
@jianyunt any word on when we will see the official WMF 5.1 RTM download package? I did some searching this morning and don't see anything other then preview releases.

**Comment by jianyunt** [comment] 2016-11-04 16:17
@jsco2t, I cannot tell the date but we are internally testing it.
By the way, if you need the fix for your downlevel machines, you can update the packageManagement module from the PowerShellGallery.com.

**Comment by rdean716** [comment] 2017-03-30 18:12
Just recently we've noticed that this issue has resurfaced on Windows 2012 R2 with WMF5.1 installed.  Would you prefer that I create a new issue for the behavior in question?  Although it is exactly this problem again.

**Comment by jianyunt** [comment] 2017-09-06 19:39
This issue seems to be fixed and hence closing.

**Closed by jianyunt** 2017-09-06 19:39 UTC
Labels: bug, Fixed
