### ISSUE TITLE
Using PowerShellGet with VSTS Package Manager

### ISSUE THREAD

**Issue by Glober777** [OneGet/oneget#174] opened 2016-03-28 16:42 UTC
Dear Team,

Is it possible to host a PowerShell Repository on a Visual Studio Team Services online service with the MS Package Manager add-on installed?

I was able to register that as a PSRepository, however when I'm trying to push a module I'm getting the following error:
Publish-PSArtifactUtility : Failed to publish module '<Modulename>': 'Cannot prompt for input in non-interactive mode.
'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:853 char:17
-                 Publish-PSArtifactUtility -PSModuleInfo $moduleInfo `
-                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [Write-Error], WriteErrorException
  - FullyQualifiedErrorId : FailedToPublishTheModule,Publish-PSArtifactUtility

Thanks!

**Comment by quoctruong** [comment] 2016-04-04 18:17
@Glober777 In order to publish a module, PowerShellGet needs to have nuget.exe. Since the machine does not have nuget.exe, PowerShellGet will prompt the user to install it. However, it seems you are running in non-interactive mode so the prompt fails.

In the future, we will add an option where Publish-Module -Force will install nuget.exe to you without prompting. However, that is not available now and as a workaround, you can try to run this command before running Publish-Module (you only need to run this once per machine):

```
Invoke-WebRequest -Uri "http://go.microsoft.com/fwlink/?LinkID=690216&clcid=0x409" -OutFile "C:\ProgramData\Microsoft\Windows\PowerShell\PowerShellGet\NuGet.exe"
```

**Comment by Glober777** [comment] 2016-04-08 13:52
@quoctruong Thank you for your suggestion. Now I'm getting another error which is related to NuGet ApiKey being incorrect. The thing is that the proposed example suggest doing two things:
1. Adding a repo using 'nuget sources add' with -username and -password parameters
2. Use VSTS as the ApiKey when pushing packages to the reporsitory

I tried using the password as the APIKey and that still doesn't work. Do you have any more suggestions?

Oh, and by the way, does PowerShellGet support NuGet 3.3+ repositories? It has a slightly different source URI and as far as I understand it also offers VSTS Credential Provider

Thanks a lot!

**Comment by iainbrighton** [comment] 2016-04-08 17:00
I cannot get the VSTS Package Manager add-on either. I get the `Publish-PSArtifactUtility : Failed to publish module 'VirtualEngine.Database': 'Cannot prompt for input in non-interactive mode.` error as well. I have the feed set to `NuGet 2.x or Visual Studio earlier versions`. Here's the output:
```powershell
[3] C:\..\Dropbox\PowerShell\> Publish-Module -Name VirtualEngine.Database -Repository VirtualEngine -NuGetApiKey VSTS -Verbose
VERBOSE: Repository details, Name = 'VirtualEngine', Location =
'https://virtualengine.pkgs.visualstudio.com/DefaultCollection/_packaging/VirtualEngine/nuget/v2/api/v2/'; IsTrusted =
'True'; IsRegistered = 'True'.
VERBOSE: Repository details, Name = 'VirtualEngine', Location =
'https://virtualengine.pkgs.visualstudio.com/DefaultCollection/_packaging/VirtualEngine/nuget/v2/api/v2/'; IsTrusted =
'True'; IsRegistered = 'True'.
VERBOSE: Publish
Location:'https://virtualengine.pkgs.visualstudio.com/DefaultCollection/_packaging/VirtualEngine/nuget/v2/api/v2/packag
e/'.
VERBOSE: Module 'VirtualEngine.Database' was found in
'C:\Users\iainb\Dropbox\PowerShell\Modules\VirtualEngine.Database'.
VERBOSE: Loading module from path
'C:\Users\iainb\AppData\Local\Temp\1375725445\VirtualEngine.Database\VirtualEngine.Database.psm1'.
VERBOSE: Repository details, Name = 'VirtualEngine', Location =
'https://virtualengine.pkgs.visualstudio.com/DefaultCollection/_packaging/VirtualEngine/nuget/v2/api/v2/'; IsTrusted =
'True'; IsRegistered = 'True'.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'VirtualEngine'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is
'https://virtualengine.pkgs.visualstudio.com/DefaultCollection/_packaging/VirtualEngine/nuget/v2/api/v2/items/psscript/
' and PackageManagementProvider is 'NuGet'.
VERBOSE: Total package yield:'0' for the specified package 'VirtualEngine.Database'.
VERBOSE: Repository details, Name = 'VirtualEngine', Location =
'https://virtualengine.pkgs.visualstudio.com/DefaultCollection/_packaging/VirtualEngine/nuget/v2/api/v2/'; IsTrusted =
'True'; IsRegistered = 'True'.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'VirtualEngine'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is
'https://virtualengine.pkgs.visualstudio.com/DefaultCollection/_packaging/VirtualEngine/nuget/v2/api/v2/' and
PackageManagementProvider is 'NuGet'.
VERBOSE: Total package yield:'0' for the specified package 'VirtualEngine.Database'.
VERBOSE: Performing the operation "Publish-Module" on target "Version '1.1.1' of module 'VirtualEngine.Database'".
Publish-PSArtifactUtility : Failed to publish module 'VirtualEngine.Database': 'Cannot prompt for input in
non-interactive mode.
'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:896 char:17
+                 Publish-PSArtifactUtility -PSModuleInfo $moduleInfo `
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : FailedToPublishTheModule,Publish-PSArtifactUtility

```

**Comment by quoctruong** [comment] 2016-04-11 22:50
@iainbrighton Have you tried this ```Invoke-WebRequest -Uri "http://go.microsoft.com/fwlink/?LinkID=690216&clcid=0x409" -OutFile "C:\ProgramData\Microsoft\Windows\PowerShell\PowerShellGet\NuGet.exe" ``` before using the add-on?
@bmanikm Hi Manik, do you have any suggestino for @Glober777

**Comment by bmanikm** [comment] 2016-04-13 00:38
@Glober777 PowerShellGet is not yet supported in below mentioned scenario:

- Is it possible to host a PowerShell Repository on a Visual Studio Team Services online service with the MS Package Manager add-on installed?
- Does PowerShellGet support NuGet 3.3+ repositories? It has a slightly different source URI and as far as I understand it also offers VSTS Credential Provider

**Comment by iainbrighton** [comment] 2016-04-13 08:49
@quoctruong Yes - I tried that but it didn't work. So this isn't a supported scenario? Is it on the roadmap?

**Comment by bmanikm** [comment] 2016-04-13 21:38
@iainbrighton Yes, it is on the roadmap.

**Comment by bmanikm** [comment] 2016-04-15 22:12
@iainbrighton Could you please provider more details on how you are trying to use the PowerShellGet module with VSTS Package Manager? 
If possible, could you please provide the instructions/steps, so that we will ensure that PowerShellGet works in your scenario?

**Comment by iainbrighton** [comment] 2016-04-18 09:02
@bmanikm In short, I'm trying to use the VSTS Package Manager as an internal repository for our internal PowerShell modules/cmdlets as well. I have only tried this on a Windows 10 client, and was hoping to leverage the VSTS Package Manager without having to stand up another NuGet feed just for PowerShell code.

**Comment by Glober777** [comment] 2016-04-18 10:02
@bmanikm Pretty much the same thing applies here. The only other thing to add is that, I'm also looking into a way to be able to configure the cloud Package Manager as a trusted source on our servers to have a single source of internal scripts\modules.

**Comment by timhaintz** [comment] 2016-06-20 11:52
@bmanikm thanks for the info on this. I understand VSTS Package Management is still preview. If/when this is officially released, will PowerShellGet be supported on it? You said earlier, it was on the road-map. Are they running in parallel or completely separate? I am really looking to vendor our PowerShell modules and VSTS is a really elegant solution for us. 
Usage is:
publish-module -Name <module name> -NuGetAPIKey <Currently only have UserName and Password option>

@Glober777 I found this article: http://stackoverflow.com/questions/35296482/invalid-web-uri-error-on-register-psrepository to enable publishing an HTTPS repository.

**Comment by OliverMartini** [comment] 2016-06-22 16:53
Hi, I have been following this thread. @Glober777, @iainbrighton, has either one of you successfully added VSTS as a PowerShell Module feed? If yes, what were your steps involved?

I am able to add VSTS Package feed as PSRepository. I executed the following cmd to publish and get the following error:
`C:\> Publish-Module -Path MyModuleDirectory -Repository NVGallery -NuGetApiKey "_MY_API_KEY"`
I used VSTS to create a Personal Access Token that I use to authenticate.

```
Publish-PSArtifactUtility : Failed to publish module 'MyModule': 'Response status code does not indicate
success: 401 (Unauthorized).
'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:853 char:17
+                 Publish-PSArtifactUtility -PSModuleInfo $moduleInfo `
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : FailedToPublishTheModule,Publish-PSArtifactUtility
```

**Comment by timhaintz** [comment] 2016-06-22 23:05
Hi @OliverMartini , if you use this article: http://stackoverflow.com/questions/35296482/invalid-web-uri-error-on-register-psrepository it is the code to create your own module. If you call this module, you can add an HTTPS repository such as in VSTS. I have done this successfully. 
To publish the module, I had to use the NuGet process, not the publish-module process. https://docs.nuget.org/create/creating-and-publishing-a-package

Browse to the module file/folder that you want to package up.
PowerShellPrompt> NuGet spec 
Modify the NuGet spec file with the information you need in it. This is called: Package.nuspec
PowerShellPrompt> nuget push yourpackage.nupkg -Source https://<your.source> -ApiKey VSTS

This worked for me and published the package to our Visual Studio site. publish-module isn't supported on VSTS yet.

Hope this helps. Thanks, Tim.

**Comment by OliverMartini** [comment] 2016-06-27 13:47
@timhaintz, thanks for your help. I was able to create the nuget package and push it to the VSTS feed.

Are you able to install the module by using install-module cmdlet after you added the repository with the Register-PSRepositoryFix cmdlet?

**Comment by bmanikm** [comment] 2016-06-27 23:26
@timhaintz, Yes, I have added the VSTS PackageManagement feed support in the PowerShellGet module. 
This support will be included in the next release of Windows Server 2016 and also in WMF 5.1 Preview.

**Comment by timhaintz** [comment] 2016-07-02 23:34
Thanks @bmanikm, looking forward to it.
@OliverMartini, I have been on leave for a couple of weeks. I haven't tried the install-module. I'm back this week, will try it and update results here. Glad the nuget bits worked.

**Comment by CodeCyclone** [comment] 2016-07-11 18:16
@bmanikm, Are there any specific steps to follow for registering the repository? I know typically for VSTS feeds you have to pass the VSTS API Key also its ideal if the VSS CredentialProvider is installed next to nuget.exe. Are you using the VSTS NuGet bootstrapper to handle these dependencies?

**Comment by timhaintz** [comment] 2016-07-12 03:16
Hi @OliverMartini , I just tried install-module via PowerShell. It fails because I assume it doesn't have credentials to connect to our VSTS repo. 
Error via verbose logging is: 
WARNING: Unable to resolve package source
'https://nameofsetuprepo.pkgs.visualstudio.com/_packaging/NuGetRepoName/nuget/v3/index.json'.
VERBOSE: Total package yield: '0' for the specified package 'PackageName'.
@bmanikm , are the credentials to connect to VSTS going to be added into PowerShellGet or will it use the NuGet credentials?
Thanks, Tim.

**Comment by vercellone** [comment] 2016-10-24 21:07
@CodeCyclone

Based on [nuget.tests.ps1](https://github.com/OneGet/oneget/blob/b84db7f72fcc130a122189b31a268d1876138c50/Test/ModuleTests/tests/nuget.tests.ps1), I was able to successfully register, find, and install a module published to my VSTS feed.  I believe the key is to use a /v2 (not /v3/index.json) -SourceLocation and either always specify -Credential or configure the [Nuget Auth Helper](https://www.visualstudio.com/en-us/docs/package/nuget/auth#vsts-auth-helper).
```PowerShell
# $PSVersionTable.PSVersion.ToString() = 5.1.14393.187
# (Get-Module PowerShellGet).Version.ToString() = 1.0.0.1
#
$password = ConvertTo-SecureString 'yourvststoken' -AsPlainText -Force
$vstsCredential = New-Object System.Management.Automation.PSCredential 'yourvstsusername', $password
Register-PSRepository -Name RepositoryName -Credential $vstsCredential -SourceLocation 'https://nameofsetuprepo.pkgs.visualstudio.com/_packaging/NuGetRepoName/nuget/v2' -InstallationPolicy Trusted
Find-Module -Name ModuleName -Repository RepositoryName -Credential $vstsCredential 
Install-Module -Name ModuleName -Repository RepositoryName -Credential $vstsCredential
```

**Comment by jianyunt** [comment] 2016-11-03 22:39
On WMF 5.1, Win10 Anniversary, and Windows Server 2016, you should be able to register-psrepository to your path. We support NuGet V2 protocols. As @vercellone mentioned, /v2 is needed.

**Comment by CodeCyclone** [comment] 2016-11-30 00:17
@vercellone and @jianyunt I confirmed the steps @vercellone provided worked on a WMF 5.1 environment. I noticed the -Credential argument only exists in WMF 5.1 or later. Thanks for you help on this. I believe this issue can be marked as closed unless others disagree.

**Comment by jianyunt** [comment] 2016-11-30 18:01
thanks!

**Closed by jianyunt** 2016-11-30 18:01 UTC
Labels: Investigate
