### ISSUE TITLE
Save-Package for Nuget provider downloads lots of dependencies

### ISSUE THREAD

**Issue by cage200** [OneGet/oneget#389] opened 2018-10-17 13:14 UTC
Hi guys,

A nuget package has dependencies.The first level dependencies are the ones which you normally expect to be downloaded.

But the command 
`Save-Package  -Name NLog -RequiredVersion 4.5.10 -Path "C:\Temp"`
  
will download all the frameworks dependencies. I got 110 packages for this command and I assume it is different from machine to machine. 

I get  packages like the ones below:
"System.IO.Compression.ZipFile
System.Security.Cryptograph...
runtime.debian.8-x64.runtim...
runtime.debian.9-x64.runtim...
runtime.fedora.23-x64.runti...
runtime.fedora.24-x64.runti...
runtime.fedora.27-x64.runti...
runtime.fedora.28-x64.runti...
runtime.opensuse.13.2-x64.r...
runtime.opensuse.42.1-x64.r...
runtime.opensuse.42.3-x64.r...
runtime.osx.10.10-x64.runti...
runtime.rhel.7-x64.runtime....
runtime.ubuntu.14.04-x64.ru..."

Is this the intent of the command ? Can I limit it somehow only for a framework  ? 
Also it will be nice to have a full flag to skip dependencies like in #232 or just to download those existing on the source used.

**Comment by alerickson** [comment] 2018-11-29 23:43
This is expected behavior.  I'll close this issue since it's a duplicate of #232 and is already linked there.

**Closed by alerickson** 2018-11-29 23:43 UTC
