### ISSUE TITLE
Packages which depend on unlisted modules cannot be installed or saved 

### ISSUE THREAD

**Issue by bmanikm** [OneGet/oneget#361] opened 2018-05-24 23:05 UTC
_From @MaximoTrinidad on May 24, 2018 20:32_

I've been seen this for sometime with one particular package:
```
Microsoft.SqlServer.SqlManagementObjects
```
But, just to find our that it wasn't only one package.

## Expected Behavior

To install the package successfully.

## Current Behavior

It can't install due to missing dependencies:
```
install-package : Unable to find dependent package(s) (System.Reflection.Emit.Lightweight)
At line:1 char:1
+ install-package -Name Microsoft.SqlServer.SqlManagementObjects -force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (System.Reflection.Emit.Lightweight:String) [Install-Package], Exception
+ FullyQualifiedErrorId : UnableToFindDependencyPackage,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

## Possible Solution

I could not find a workaround as I can't even use the Save-Package cmdlet
```
PS /home/maxt> save-package -Name Microsoft.SqlServer.SqlManagementObjects -path /home/maxt/Downloads                   
WARNING: Unable to find dependent package(s) (System.Reflection.Emit.Lightweight)
WARNING: Unable to find dependent package(s) (System.Reflection.Emit)
WARNING: Unable to find dependent package(s) (System.Xml.XDocument)
WARNING: Unable to find dependent package(s) (System.Threading.Timer)
WARNING: Unable to find dependent package(s) (System.Threading.Thread)
WARNING: Unable to find dependent package(s) (runtime.native.System.Data.SqlClient.sni)
save-package : Unable to save the package 'Microsoft.SqlServer.SqlManagementObjects.140.17265.0.nupkg'.
At line:1 char:1
+ save-package -Name Microsoft.SqlServer.SqlManagementObjects -path /ho ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Microsoft.Power...ets.SavePackage:SavePackage) [Save-Package], Exception
+ FullyQualifiedErrorId : ProviderFailToDownloadFile,Microsoft.PowerShell.PackageManagement.Cmdlets.SavePackage
```

## Steps to Reproduce (for bugs)

Try to install the following packages in Linux:

- Microsoft.SqlServer.SqlManagementObjects
- NETStandard.Library

1. sudo pwsh
2. install-package -Name Microsoft.SqlServer.SqlManagementObjects -force
3. install-package -Name NETStandard.Library -force

Installation error on both packages:
```
install-package : Unable to find dependent package(s) (System.Reflection.Emit.Lightweight)
```

## Your Environment
Linux
```
[maxt@mercury ~]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

```PowerShell
PS /home/maxt> $PSVersionTable                                                                                          

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Linux 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS /home/maxt> Get-Module                                                                                               

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemPropert...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     1.1.7.2    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-Pack...
Script     1.6.5      PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCap...
Script     1.2        PSReadLine                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PS...

PS /home/maxt> Get-Module -ListAvailable PowerShellGet,PackageManagement                                                


    Directory: /usr/local/share/powershell/Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.1.7.2    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-Packa...
Script     1.6.5      PowerShellGet                       {Find-Command, Find-DSCResource, Find-Module, Find-RoleCap...


    Directory: /opt/microsoft/powershell/6.1.0~preview.2/Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.1.7.0    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-Packa...

PS /home/maxt> Get-PackageProvider                                                                                      

Name                     Version          DynamicOptions
----                     -------          --------------
NuGet                    2.8.5.210        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag...
PowerShellGet            1.6.5.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, ...

PS /home/maxt> Get-PackageProvider -ListAvailable                                                                       

Name                     Version          DynamicOptions
----                     -------          --------------
NuGet                    2.8.5.210        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag...
PowerShellGet            1.6.5.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, ...
```
![powershellget_pkgissue_2018-05-24_16-21-07](https://user-images.githubusercontent.com/19892435/40512146-db27987e-5f6f-11e8-803c-33c1d16e04f6.jpg)

_Copied from original issue: PowerShell/PowerShellGet#286_

**Comment by bmanikm** [comment] 2018-05-24 23:05
_From @MaximoTrinidad on May 24, 2018 20:44_

@SteveL-MSFT / @joeyaiello 

I'm tagging you both just in case PowerShell Core has to do with this issue to.
I have no issues with Windows!

:)

**Comment by bmanikm** [comment] 2018-05-24 23:06
This is a duplicate of https://github.com/OneGet/oneget/issues/322.

It looks like all the versions of System.Reflection.Emit.Lightweight  and System.Reflection.Emit packages got unlisted on NuGet.org.

```PowerShell
PS C:\> Find-Package -ProviderName NuGet -Source https://nuget.org/api/v2 -AllowPrereleaseVersions System.Reflection.Emit.Lightweight
Find-Package : No match was found for the specified search criteria and package name 'System.Reflection.Emit.Lightweight'. Try Get-PackageSource to see all available registered package sources.
At line:1 char:1
+ Find-Package -ProviderName NuGet -Source https://nuget.org/api/v2 -Al ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ets.FindPackage:FindPackage) [Find-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.FindPackage

PS C:\> Find-Package -ProviderName NuGet -Source https://nuget.org/api/v2 -AllowPrereleaseVersions System.Reflection.Emit
Find-Package : No match was found for the specified search criteria and package name 'System.Reflection.Emit'. Try Get-PackageSource to see all available registered package sources.
At line:1 char:1
+ Find-Package -ProviderName NuGet -Source https://nuget.org/api/v2 -Al ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ets.FindPackage:FindPackage) [Find-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.FindPackage

PS C:\>
PS C:\> Find-Package -ProviderName NuGet -Source https://nuget.org/api/v2 -AllowPrereleaseVersions System.Reflection.Emit.Lightweight -RequiredVersion 4.3.0

Name                           Version          Source                           Summary
----                           -------          ------                           -------
System.Reflection.Emit.Ligh... 4.3.0            https://nuget.org/api/v2         Provides the System.Reflection.Emit.DynamicMethod class, which represents a dynamic method that can be compiled, executed, and


PS C:\> Find-Package -ProviderName NuGet -Source https://nuget.org/api/v2 -AllowPrereleaseVersions System.Reflection.Emit -RequiredVersion 4.3.0

Name                           Version          Source                           Summary
----                           -------          ------                           -------
System.Reflection.Emit         4.3.0            https://nuget.org/api/v2         Provides classes that allow a compiler or tool to emit metadata and optionally generate a PE file on disk. The primary clients
```

**Comment by MaximoTrinidad** [comment] 2018-06-05 23:09
OK Everyone! Here's an update...

I realized that Nuget has another version out there: **Microsoft.SqlServer.SqlManagementObjects 140.17267.0-preview**

I decided to installed it on my Windows 10 WSL Ubuntu PowerShell Core and it did installed fine. 

![windowswsl_smo_2018-06-05_18-56-58](https://user-images.githubusercontent.com/19892435/41007112-56143386-68f2-11e8-9a67-054f2cca2916.jpg)

**_BUT!! If I try in any other full distribution of Linux (like CentOS) and MacOS. It keeps failing!_**

```
Install-Package -name Microsoft.SqlServer.SqlManagementObjects -AllowPrerelease
```
![centos_smofailed_2018-06-05_18-59-25](https://user-images.githubusercontent.com/19892435/41007263-f78cdc5e-68f2-11e8-82d0-6589e922548f.jpg)

![macos_smofailed_2018-06-05_18-59-25](https://user-images.githubusercontent.com/19892435/41007286-0d66ad5c-68f3-11e8-877d-b75ad0a78b4e.jpg)

```
PS /home/maxt> cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

PS /home/maxt> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Linux 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
```
PS /Users/maxt> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.5
BuildVersion:	17F77

PS /Users/maxt> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Darwin 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-45...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Someone need to include PowerShell Core Nuget testing on their QA steps.  This been going too long! There are a lot of people wanted to try this SMO package for cross-platform script. 

Any HELP!!
:)

**Comment by edyoung** [comment] 2018-06-07 04:37
As @bmanikm bmanikm mentions above we think this is due to all the versions of  System.Reflection.Emit.Lightweight and System.Reflection.Emit packages having recently been unlisted on nuget.org (see https://github.com/dotnet/corefx/issues/29365 for the backstory on that). I can't understand why the behavior would be different between different distributions - maybe you already had those packages installed locally on your WSL box.  We are looking at this issue but your best short-term workaround would be to use nuget.exe to install the packages you want

**Comment by bgavrilMS** [comment] 2018-06-07 23:19
Is this the root cause issue for not being able to use Install-Package on a package with unlisted dependencies? This seems to be breaking a lot of people, including https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1081

**Comment by edyoung** [comment] 2018-06-07 23:36
This issue covers modifying install-package to allow installing a module even if all the versions of a dependency are unlisted. The current behavior has been there forever but the recent unlisting of those popular packages has caused a lot more real-world issues.

**Comment by cage200** [comment] 2018-10-12 18:45
It will be nice if Save-Packages will have a flag -SkipDependencies.

**Comment by edyoung** [comment] 2018-10-12 19:05
@cage200 that seems unrelated to this issue?

**Comment by edyoung** [comment] 2019-05-12 20:46
resolved by the change above

**Closed** 2019-05-12 20:46 UTC
