### ISSUE TITLE
List of desired package manager plugins for OneGet

### ISSUE THREAD

**Issue by fearthecowboy** [OneGet/oneget#77] opened 2014-11-10 19:20 UTC
### OneGet is a package management aggregator.

In order to fill out the goal of comprehensive package management in Windows, we need to come up with a list of package providers (types of existing package managers) that we'd like to see plugins created for OneGet for.

The list starts off fairly easy, but we need to get as much of these captured as possible.

## Package Managers

Package Manager | Assigned To | Project Page | Notes
------------ | ------------- | ------------- | ------------- 
PSModule | manikb | (none) | PowerShell Get package manager for powershell modules.
MSI | @FearTheCowboy | [OneGet](https://github.com/oneget/oneget) | Included in OneGet core 
MSU | @FearTheCowboy | [OneGet](https://github.com/oneget/oneget)| Included in OneGet core 
BootStrap | @FearTheCowboy | [OneGet](https://github.com/oneget/oneget)| Included in OneGet core. Set to `automation-only`
ARP (Add/remove programs) | @FearTheCowboy | [OneGet](https://github.com/oneget/oneget)| Included in OneGet core -- Does not currently support installation, just removal. 
EXE | unassigned | (none) | Should detect known EXE installers to provide consistent usage.( ie, detecting NSIS packages, InstallShield packages, etc...)
[NuGet](http://nuget.org/) | @FearTheCowboy | [OneGet/NuGet](https://github.com/oneget/nuget) | Bootstraps off the web. Will get set to `automation-only` by default.
[Chocolatey](http://chocolatey.org/) | @FearTheCowboy | [OneGet/NuGet](https://github.com/oneget/nuget) | Current implementation is included with the NuGet provider -- this can be changed to support the Official Chocolatey version when it is ready to replace the current one.
WindowsUpdate | unassigned| (none) | `Idea` A package manager for Windows Update (and supports WSUS) to find and install updates for Windows. from @p0w3rsh3ll:  I'd split WindowsUpdate into: WSUS catalog (on-premise), Windows Update and Microsoft Update. http://t.co/fcMBVWwc71
WindowsStore | unassigned | (none) | `Idea` A package manager for Windows Store Applications (.appx)
[Cygwin](https://www.cygwin.com/) | unassigned | (none) | support for installing packages into a cygwin installation.
[Ruby Gems](https://rubygems.org) | unassigned | (none) | support for installing Ruby Gems. 
[Node's NPM](https://npmjs.org) | unassigned | (none) | support for installing Node JS packages.
[Perl's CPAN](http://www.cpan.org) | unassigned | (none) | support for installing PERL packages from CPAN.
[Python](https://pypi.python.org/pypi) | unassigned | (none) | support for installing Python packages from Pypi (uh, and `easyinstall` and `PIP`)
[PEAR](http://pear.php.neti) | unassigned | (none) | PEAR is a framework and distribution system for reusable PHP components..
[PECL](http://pecl.php.net) | unassigned | (none) | PECL is a repository for PHP Extensions, providing a directory of all known extensions and hosting facilities for downloading and development of PHP extensions.
[Composer](https://getcomposer.org) | unassigned | (none) | Composer is a tool for dependency management in PHP. It allows you to declare the dependent libraries your project needs and it will install them in your project for you.
[Maven](https://maven.apache.org/what-is-maven.html) | unassigned | (none) | a standard (Java) way to build the projects, a clear definition of what the project consisted of, an easy way to publish project information and a way to share JARs across several projects..
[LUADist](http://luadist.org) | unassigned | (none) | LuaDist is a true multi-platform package management system that aims to provide both source and binary repository of modules for the Lua programming language.
[LUA](http://luarocks.org) | unassigned | (none) |This is LuaRocks, a deployment and management system for Lua modules.
[CPM](https://github.com/iauns/cpm) | unassigned | (none) |A C++ Package Manager based on CMake and Git. (Any info on pacm? )
[Cargo/Rust](http://doc.crates.io) | unassigned | (none) |Cargo is a tool that allows Rust projects to declare their various dependencies, and ensure that you'll always get a repeatable build.
[Bower](http://bower.io) | unassigned | (none) | Bower works by fetching and installing packages from all over, taking care of hunting, finding, downloading, and saving the stuff you’re looking for. Bower keeps track of these packages in a manifest file, bower.json. How you use packages is up to you. Bower provides hooks to facilitate using packages in your tools and workflows.
[Pathogen/Vim](http://www.vim.org/scripts/script.php?script_id=2332) | unassigned | (none) |Manage your 'runtimepath' with ease.  In practical terms, pathogen.vim makes it super easy to install plugins and runtime files in their own private directories
ClickOnce | unassigned | (none) | Applications installed via ClickOnce 
VSIX | unassigned | (none) | Visual Studio Extensions. Would be awesome if it could scrape the gallery as a `package source`
Github Gist | @dfinke | (none) | A package provider that pulls packages from github gists! 
AppV | unassigned | (none) | Install AppV packages (yes, very cool).
WebPI | unassigned | (none) | Microsoft's Web Platform Installer.
Azure Gallery | unassigned | (none) | Azure Gallery (?).
Windows Features| unassigned | (none) | Windows Features (ie, CBS or DISM).?
SCCM | unassigned | (none) | System Center Config Manager packages 

``` markdown
# using the format:
[$NAME]($WEB) | unassigned | (none) | $DESCRIPTION.
```

OneGet also supports pluggable archive formats:

## Archive Formats
Format | Assigned To | Project Page | Notes
------------ | ------------- | ------------- | ------------- 
CAB | @FearTheCowboy |[OneGet](https://github.com/oneget/oneget) | CAB files. Support for this borrowed from the DTF.
ZIP | @FearTheCowboy | [OneGet](https://github.com/oneget/oneget) | Zip Files. Support for this borrowed from the DTF.
TAR | unassigned | (none) | Unix TAR files
GZIP | unassigned | (none) | Unix gzip (.gz) files
7Zip | unassigned | (none) | 7Zip files
RAR | unassigned | (none) | RAR files

As well as pluggable downloader schemes:

## Downloaders
Format | Assigned To | Project Page | Notes
------------ | ------------- | ------------- | ------------- 
FTP/HTTP/HTTPS/File| @FearTheCowboy |[OneGet](https://github.com/oneget/oneget) | Built in support for standard protocols. Current implementation is pretty rudimentary. Should add support for `SmartScreen`.
SSH/SCP | unassigned | (none) | Support for grabbing files from SSH/SCP

### Remember:
Package Providers can leverage other package providers in their implementation (ie, the `PSModule` provider uses the `NuGet` Provider and the `Chocolatey` uses the `MSI`, `MSU` and `VSIX` Providers

Please feel free to add any package manager to this list (just specify the details in this thread, I'll edit this post, and then delete your message)

**Comment by rzander** [comment] 2015-04-14 20:00
Another one is born...
Package Manager: [RuckZuck](http://ruckzuck.tools)
Assigned To: @rzander
Project Page: http://ruckzuck.codeplex.com
Notes: Support for installation, update (e.g. Find-Package -Updates) and removal is implemented.

**Comment by fearthecowboy** [comment] 2015-04-14 21:07
@rzander  Oh, very cool.

I'm tied up today, but I'll play around with this tomorrow. If it's stable enough, I'd like to get it into the list of available providers that can autobootstrap. 

G

**Comment by bastianeicher** [comment] 2015-05-07 23:40
The Package Provider for [Zero Install](http://0install.de/) is ready. It supports `Find-Package`, `Get-Package`, `Install/Uninstall-Package`, `Save-Package` and `Register/Unregister/Set-PackageSource`.

The Provider is bundled with Zero Install 2.8+ and registered via the `HKCU\SOFTWARE\Microsoft\PackageManagement` registry key. An installer that runs without Admin privileges is available at: https://0install.de/files/zero-install-per-user.exe

@fearthecowboy I'd love to see this added to the bootstrap list. Please let me know if you need any additional information.

**Comment by fearthecowboy** [comment] 2015-05-11 16:55
@bastianeicher  AWESOME!

I'm just recovering from the worst flu I've had in like forever, gimme a day or so, and we'll work on getting this into the bootstrapper list.  Lemme take a look, and see if we need to sync up over skype.

G

**Comment by bastianeicher** [comment] 2015-05-12 10:18
@fearthecowboy I wish you a speedy recovery.
My Skype handle is bastian.eicher. I'm in the CEST timezone, 9 hours behind PDT, so a good timeframe to get in touch would probably be between 8AM and 1PM PDT.

**Comment by fearthecowboy** [comment] 2015-05-19 14:00
@bastianeicher I finally got around to playing with the 0install provider. Pretty damn cool.

I have two requests:

**Comment by fearthecowboy** [comment] 2015-05-19 15:55
@bastianeicher couple more points of feedback - 
 - You probably shouldn't bother with progress messages in find-package. It's kinda noisy, and the downloads for the metadata seem fast enough.
- find-package with a blank name should return all the results. A lot of people use that for discovering what's available

**Comment by bastianeicher** [comment] 2015-05-19 16:46
@fearthecowboy 

* 0install has a self-updating feature that itself uses the 0install package format and can update both "installed" and "portable" instances of Zero Install. This would most likely conflict with Windows Installer's resiliency/self-repair feature, since it would see a self-updated instance as damaged and try to revert it. I could create an MSI that simply wraps the current EXE installer but that seems like a rather hacky solution. :(

* Correct, it's an open-source project currently with next to no funds (e.g. for buying an Authenticode certificate). There's a `build.cmd` script in the [Git repo](https://github.com/0install/0install-win) that compiles the source and produces an installer and a [CI server](https://0install.de/teamcity/) so automating the build shouldn't be a problem.

* The provider ties into 0install's existing progress-reporting infrastructure which generally reports anything that does network IO. I suppose I could modify the provider to filter out low-impact/noisy events such as metadata retrieval.

* Thanks for the `Find-Package` hint, I'll modify that.
  * I was also wondering whether the `-SearchMirror` option I added was sensibly named and discoverable enough. It tells the provider to query a global mirror listing all known 0install packages rather than just those in the registered package sources.

**Comment by fearthecowboy** [comment] 2015-05-19 19:16
@bastianeicher 

Hmm. Supporting an exe install for providers is coming, just not soon enough.  I couldn't get it in before the cutoff for the win10 client.

Sadly, that MSI => EXE shim, while hacky, would allow us to get past that. I can't think of a simpler workaround in the short run. Hmmmm.

I found the `-SearchMirror` simply enough. I don't think you need to do anything different there.

**Comment by bastianeicher** [comment] 2015-05-31 17:08
@fearthecowboy

I've just released Zero Install for Windows 2.8.2 some minor bug fixes and tweaks. The build process now also generates an MSI wrapping the the EXE installer: http://0install.de/files/zero-install-per-user.msi

How do we go about creating a signed version of the MSI?

**Comment by oising** [comment] 2015-06-01 15:49
I see that Windows 10 ships with a DISM module. It should be renamed DISMal though. It's horridly un-powershelly.

**Comment by bastianeicher** [comment] 2015-06-03 13:59
@fearthecowboy

Zero Install is mostly used for adding apps to the current user profile without requiring admin privileges. Therefore, bootstrapping the [per-user setup for Zero Install](http://0install.de/files/zero-install-per-user.msi) fits nicely.

Zero Install also supports creating entry points for all users (exposed via the `-MachineWide` option in the OneGet provider). This only works if the [machine-wide setup for Zero Install](http://0install.de/files/zero-install.msi) was used instead, which installs additional stuff like a Windows service for safely sharing binaries between users.

So if a first time user runs `Install-Package vlc -Provider 0install -MachineWide` they'd get a somewhat suboptimal experience of having per-user Zero Install automatically installed and then being told they actually need to get a different setup instead if the want to use the machine-wide feature.

Maybe I should create separate `0install` and `0install-machine-wide` providers?

**Comment by bastianeicher** [comment] 2015-06-29 09:01
Is there any news regarding the bootstrap list? I'd love to see 0install added before Windows 10 RTMs. :)

**Comment by fearthecowboy** [comment] 2015-07-06 16:30
Sorry for the delay; I've been temporarily seconded onto another project, (and all the rush up to the shipping of Win10 client has stretched my time mighty slim)

Stay tuned--we're trying to work out some details fairly shortly.

**Comment by bastianeicher** [comment] 2015-08-11 21:58
I have now acquired my own code signing certificate. The following MSIs are AuthentiCode-signed and ready for inclusion in the OneGet bootstrap list:
`0install`: http://0install.de/files/zero-install-per-user.msi
`0install-Machine`: http://0install.de/files/zero-install.msi

**Comment by bastianeicher** [comment] 2015-08-29 15:47
@fearthecowboy Any news on this?

**Comment by xumins** [comment] 2015-09-11 17:59
Bastianeicher, Krishna will contact you shortly to discuss how to include your provider into the bootstrap list.

**Comment by xumins** [comment] 2015-09-11 18:13
@bastianeicher , @KrishnaV-MSFT will contact you shortly.

**Comment by dreamcat4** [comment] 2015-09-30 10:50
+1
Need cygwin provider for duplicity and irssi.

**Comment by bastianeicher** [comment] 2015-10-02 13:41
@KrishnaV-MSFT Haven't heard from you yet. Any estimate when we could get 0install into the bootstrap list?

**Comment by KrishnaV-MSFT** [comment] 2015-10-05 18:09
Hi Bastian,

Thanks for your interest in integrating with PackageManagement provider. Given the project timelines and the number of issues we are finding in PackageManagement/OneGet core, at this point we are considering only supporting assemblies or PowerShell modules as PackageManagement providers. We discussed about this during our community meeting on 9/22.  In this context, is it possible for you to change your 0install provider to be either an Assembly or a PoweShell module? If  you choose PowerShell module route, you can publish it directly at https://www.powershellgallery.com/. If you choose the assembly route, we can add it to PackageManagement provider list.

We want to document this process and take feedback. But before we do that, I would like to take your inputs. Supporting MSI and other forms of PackageMangement providers is on our list, but at this point of time we want to prioritize supporting the two forms mentioned above.

Thanks
Krishna

**Comment by bastianeicher** [comment] 2015-10-06 13:22
Hi Krishna,

Zero Install uses a concept somewhat similar to Windows Installer's advertised shortcuts. Launching an application that was "installed" using Zero Install always goes through `0install.exe` first which performs tasks such as download-on-demand and dependency injection.

So while I could redesign the 0install OneGet Provider to be a standalone assembly anything it installed would not work unless a "regular" installation of Zero Install was also present on the system.

One possibility I see is to implement the provider as a standalone assembly that installs the rest of Zero Install on first use. Would this approach be fine for you?

Regards
Bastian

**Comment by bastianeicher** [comment] 2015-10-12 20:15
@KrishnaV-MSFT Would a single-assembly package provider that installs additional components on first use be accepted into the bootstrap list?

**Comment by KrishnaV-MSFT** [comment] 2015-10-14 00:36
Thanks Bastian. That should work.

**Comment by Jaykul** [comment] 2015-10-25 20:24
> Thanks for your interest in integrating with PackageManagement provider. Given the project timelines and the number of issues we are finding in PackageManagement/OneGet core, at this point we are considering only supporting assemblies or PowerShell modules as PackageManagement providers.

This doesn't make sense to me -- what about NuGet?

**Comment by mwrock** [comment] 2015-10-25 20:45
I interpreted this as "Assemblies" == NuGet. Not sure if that's a correct interpretation.

**Comment by bastianeicher** [comment] 2015-10-25 22:28
As far is I understand it, the issue is how OneGet acquires new providers for specific package managers on-demand (bootstrapping). The original design supported two variants:
1. Providers that consist of a single assembly (.NET DLL or EXE) that simply get downloaded to a well-known location and are then ready to use.
2. MSI or EXE installer that gets downloaded and executed by OneGet to install a provider assembly along with additional support stuff it needs.
Variant 2 is being put on ice for now.

**Comment by rismoney** [comment] 2015-10-25 22:39
Set-Alias Half-Get One-Get

**Comment by Jaykul** [comment] 2015-10-26 04:13
Yeah, ok, my point was that **Nuget** is an executable.

I guess if you consider nuget.exe the _provider_, then we need documentation of how to write an exe provider (I was assuming that the provider had to be implemented _on top of_ nuget.exe)

**Comment by bastianeicher** [comment] 2015-10-26 07:14
The NuGet provider seems to be a little sneaky in that regard: Although it is an EXE OneGet still loads it like a DLL and searches for a class that implements its provider contract. It does not actually "execute" the EXE.

Please note this is all based on what I saw in OneGet builds a few months ago. This may well have changed in the meantime.

**Comment by jianyunt** [comment] 2015-10-26 17:10
Yeah, we made some changes. The new version of Nuget provider is .dll. Check out the source code https://github.com/OneGet/NuGetProvider.  It runs on Nano server and full server.

**Comment by jianyunt** [comment] 2016-01-07 22:55
Please check out https://github.com/OneGet/oneget/wiki/Provider-Requests

**Closed by jianyunt** 2016-01-07 22:55 UTC
