### ISSUE TITLE
Disaster with Uninstall-package cmdlet USE IT WITH CAUTION

### ISSUE THREAD

**Issue by vyckou** [OneGet/oneget#181] opened 2016-05-17 09:41 UTC
Hi,

I have rewritten half of the code to make this thing do, what it ment for. Anyway, just found very "interesting" functionality of the uninstall-package cmdlet.
Anyway

Dear developers - try to launch "uninstall-package -name i -force" command on your home pc, which has Windows 10 and WMF 5.0 and chek what will happen ;)

It will rip off any /msi/chocolatey/nuget package which has i char in the package name.

Documentation in the microsoft.com:
https://technet.microsoft.com/en-us/library/dn890702.aspx
"
-Name<String[]>
Specifies one or more package names. Multiple names must be separated by commas.
"

-not it is NOT. - should be more like **Specifies FRAGMENT of package name**

Install-package - follows the dependency logics.
Uninstall-package - does random s... on your sytem.

**Comment by quoctruong** [comment] 2016-06-10 15:12
Hi @vyckou, we are working on fixing this issue. Thanks for reporting the bug.

**Comment by jianyunt** [comment] 2016-08-15 22:21
Thanks for reporting it. The issue is fixed in [WMF 5.01](https://blogs.msdn.microsoft.com/powershell/2016/07/16/announcing-windows-management-framework-wmf-5-1-preview/).

**Comment by jianyunt** [comment] 2016-10-16 01:24
The issue is fixed in Windows Sever 2016. Thanks for reporting it.

**Closed** 2016-11-03 22:44 UTC
Labels: bug, Fixed
