### ISSUE TITLE
Intermittent 503 issue with oneget.org packages

### ISSUE THREAD

**Issue by MajorSho** [OneGet/oneget#437] opened 2019-03-27 08:12 UTC
OneGet.org keeps going down (And coming back up) intermittently

We are sometimes seeing a 503 error "Service Unavailable" and then it will start working again no issues however it being unreliable today is causing some issues.

Example error from VTFS logs: 
2019-03-27T08:05:19.1414947Z WARNING: MSG:UnableToDownload «https://oneget.org/nuget-2.8.5.208.package.swidtag» «»
2019-03-27T08:05:19.4283489Z WARNING: Unable to download from URI 'https://oneget.org/nuget-2.8.5.208.package.swidtag' to ''.
2019-03-27T08:05:21.9559940Z WARNING: Unable to download from URI 'https://oneget.org/nugetv2.feed.swidtag' to ''.
2019-03-27T08:05:22.2877049Z WARNING: MSG:UnableToDownload «https://oneget.org/psl-1.0.0.210.package.swidtag» «»
2019-03-27T08:05:23.5371135Z WARNING: Unable to download from URI 'https://oneget.org/psl.feed.swidtag' to ''.

**Comment by Suzamax** [comment] 2019-03-27 09:11
I have this issue too! 😞 

```
PS C:\Windows\system32> Install-Module -Name MSOnline

Se necesita el proveedor de NuGet para continuar
PowerShellGet necesita la versión del proveedor de NuGet '2.8.5.201' o posterior para interactuar con repositorios
basados en NuGet. El proveedor de NuGet debe estar disponible en 'C:\Program
Files\PackageManagement\ProviderAssemblies' o 'C:\Users\ratio\AppData\Local\PackageManagement\ProviderAssemblies'.
También puedes instalar el proveedor de NuGet ejecutando 'Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201
 -Force'. ¿Quieres que PowerShellGet se instale e importe el proveedor de NuGet ahora?
[S] Sí  [N] No  [U] Suspender  [?] Ayuda (el valor predeterminado es "S"):
ADVERTENCIA: No se puede descargar desde el URI 'https://oneget.org/nuget-2.8.5.208.package.swidtag' a ''.
ADVERTENCIA: No se puede descargar desde el URI 'https://oneget.org/nugetv2.feed.swidtag' a ''.
ADVERTENCIA: No se puede descargar desde el URI 'https://oneget.org/psl.feed.swidtag' a ''.
```

oneget.org throws 503 too.

**Comment by MajorSho** [comment] 2019-03-27 09:38
After a bit more debugging (The intermittent state of the URL can be found below)
I have got the status code of the endpoint on average every 30 seconds.


The below log shows the 503 errors (Along with it working too).

03/27/2019 09:10:06  -  [Got a 503 response back]
03/27/2019 09:10:37  -  [Got a 503 response back]
03/27/2019 09:11:07  -  [Got a 503 response back]
03/27/2019 09:11:48  -  Got A 200 response back
03/27/2019 09:12:26  -  Got A 200 response back
03/27/2019 09:13:00  -  Got A 200 response back
03/27/2019 09:13:33  -  Got A 200 response back
03/27/2019 09:14:09  -  Got A 200 response back
03/27/2019 09:14:45  -  Got A 200 response back
03/27/2019 09:15:16  -  Got A 200 response back
03/27/2019 09:15:52  -  Got A 200 response back
03/27/2019 09:16:23  -  Got A 200 response back
03/27/2019 09:17:01  -  Got A 200 response back
03/27/2019 09:17:36  -  Got A 200 response back
03/27/2019 09:18:19  -  Got A 200 response back
03/27/2019 09:18:55  -  Got A 200 response back
03/27/2019 09:19:25  -  [Got a 503 response back]
03/27/2019 09:20:09  -  Got A 200 response back
03/27/2019 09:20:40  -  [Got a 503 response back]
03/27/2019 09:21:10  -  [Got a 503 response back]
03/27/2019 09:21:52  -  Got A 200 response back
03/27/2019 09:22:53  -  Got A 200 response back
03/27/2019 09:23:35  -  Got A 200 response back
03/27/2019 09:24:05  -  [Got a 503 response back]
03/27/2019 09:24:36  -  [Got a 503 response back]
03/27/2019 09:25:24  -  Got A 200 response back
03/27/2019 09:26:09  -  Got A 200 response back
03/27/2019 09:26:39  -  [Got a 503 response back]
03/27/2019 09:27:20  -  Got A 200 response back
03/27/2019 09:27:58  -  Got A 200 response back
03/27/2019 09:28:34  -  Got A 200 response back
03/27/2019 09:29:10  -  Got A 200 response back
03/27/2019 09:29:46  -  Got A 200 response back
03/27/2019 09:30:17  -  Got A 200 response back
03/27/2019 09:30:53  -  Got A 200 response back
03/27/2019 09:31:28  -  Got A 200 response back
03/27/2019 09:32:06  -  Got A 200 response back
03/27/2019 09:32:41  -  Got A 200 response back
03/27/2019 09:33:20  -  Got A 200 response back
03/27/2019 09:34:00  -  Got A 200 response back
03/27/2019 09:34:30  -  [Got a 503 response back]

**Comment by nixon89** [comment] 2019-03-27 10:05
I have this issue to:
Create 2 new VMs. 
On 1st VM all OK:
```
PS C:\Windows\system32> Install-PackageProvider -Name Nuget -Force -Verbose
VERBOSE: Using the provider 'Bootstrap' for searching packages.
VERBOSE: Finding the package 'Bootstrap::FindPackage' 'Nuget','','','''.
VERBOSE: Performing the operation "Install Package" on target "Package 'nuget' version '2.8.5.208' from
'https://oneget.org/nuget-2.8.5.208.package.swidtag'.".
VERBOSE: Installing the package 'https://oneget.org/nuget-2.8.5.208.package.swidtag'.
VERBOSE: Installed the package 'nuget' to 'C:\Program
Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll'.

Name                           Version          Source           Summary
----                           -------          ------           -------
nuget                          2.8.5.208        https://onege... NuGet provider for the OneGet meta-package manager
VERBOSE: Importing the package provider Nuget
VERBOSE: The provider 'NuGet' has already been imported. Trying to import it again.
VERBOSE: Loading an assembly 'C:\Program
Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll'.
VERBOSE: Imported provider 'C:\Program
Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll' .
```
On 2nd VM `UnableToResolvePackage` error:
```
PS C:\Windows\system32> Install-PackageProvider -Name Nuget -Force -Verbose
VERBOSE: Using the provider 'Bootstrap' for searching packages.
VERBOSE: Finding the package 'Bootstrap::FindPackage' 'Nuget','','','''.
WARNING: Unable to download from URI 'https://oneget.org/nuget-2.8.5.208.package.swidtag' to ''.
VERBOSE: Cannot download link 'https://oneget.org/nuget-2.8.5.208.package.swidtag', retrying for '2' more times.
VERBOSE: Cannot download link 'https://oneget.org/nuget-2.8.5.208.package.swidtag', retrying for '1' more times.
VERBOSE: Cannot download link 'https://oneget.org/nuget-2.8.5.208.package.swidtag', retrying for '0' more times.
WARNING: Unable to download from URI 'https://oneget.org/nugetv2.feed.swidtag' to ''.
VERBOSE: Cannot download link 'https://oneget.org/nugetv2.feed.swidtag', retrying for '2' more times.
VERBOSE: Cannot download link 'https://oneget.org/nugetv2.feed.swidtag', retrying for '1' more times.
VERBOSE: Performing the operation "Install Package" on target "Package 'nuget' version '2.8.5.208' from
'https://oneget.org/nuget-2.8.5.208.package.swidtag'.".
VERBOSE: Cannot download link 'https://oneget.org/nuget-2.8.5.208.package.swidtag', retrying for '2' more times.
VERBOSE: Cannot download link 'https://oneget.org/nuget-2.8.5.208.package.swidtag', retrying for '1' more times.
VERBOSE: Cannot download link 'https://oneget.org/nuget-2.8.5.208.package.swidtag', retrying for '0' more times.
Install-PackageProvider : Unable to resolve package reference 'https://oneget.org/nuget-2.8.5.208.package.swidtag'.
At line:1 char:1
+ Install-PackageProvider -Name Nuget -Force -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (https://oneget....package.swidtag:String) [Install-PackageProvider], Excep
   tion
    + FullyQualifiedErrorId : UnableToResolvePackage,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackageProv
   ider
```

**Comment by Dave3of5** [comment] 2019-03-27 11:55
Getting the same. Is this the correct forum to get this fixed ?

**Comment by rnsc** [comment] 2019-03-27 12:06
Also having this issue while trying to install Windows DSC packages.
`Failed to bootstrap provider 'https://oneget.org/nuget-2.8.5.208.package.swidtag'.`

**Comment by MajorSho** [comment] 2019-03-27 13:09
> Getting the same. Is this the correct forum to get this fixed ?
I have no idea, was thinking the same. But no idea who you would contact to report it?

**Comment by tb0111** [comment] 2019-03-27 13:25
Same issue here, seems like it's been going on for a while

**Comment by dewinterjack** [comment] 2019-03-27 13:27
It's intermittent, eventually worked for me

**Comment by OCram85** [comment] 2019-03-27 13:56
Same issue here in Appveyor, Travis and locally:

![build_job_error](https://i.imgur.com/50Zak3H.png) 
![oneget_status](https://i.imgur.com/2ymJTP1.png)

**Comment by renperez** [comment] 2019-03-27 14:26
we are having the same issue too! can someone escalate this?

**Comment by edyoung** [comment] 2019-03-27 14:41
Hi, we're aware of the issue and looking into it.

**Comment by renperez** [comment] 2019-03-27 14:45
thanks @edyoung appreciate it!

**Comment by renperez** [comment] 2019-03-27 14:46
please keep us posted here. thanks again

**Comment by jlh211** [comment] 2019-03-27 17:54
I'm experiencing the same issue with getting 503 errors. Have you guys identified the problem? Thanks!

**Comment by rarera** [comment] 2019-03-27 18:03
Hi, this is urgent as we are installing powershell modules on our prod resources in a startup script.

Questions:
Is there a way to provide multiple alternative repositories for download?
How can we install modules from the local FS on the server, without going against an external source?

Appreciate any help on this.

**Comment by renperez** [comment] 2019-03-27 18:10
any update on this? This is one of our dependencies and its causing our builds to fail.

**Comment by abjinugu** [comment] 2019-03-27 18:50
updates please !! all our releases are on hold because of this.

**Comment by edyoung** [comment] 2019-03-27 18:57
We are looking at the issue. Don't have anything useful to share. @rarera it is possible to specify internal servers or file shares as package sources, please see docs linked from powershellgallery.com for details

**Comment by 4deeptech** [comment] 2019-03-27 19:38
@edyoung or anyone else here... Could this be why Azure Pipelines Hosted VS agents aren't working right?  My hosted agents are failing to run builds(even start) so I went to go build my own Agent VM using the scripts from here: https://github.com/Microsoft/azure-pipelines-image-generation and this process for sure is broken due to the 503 issues. I thought that if my Hosted Agents aren't working I could spin up my own VM with the agent image and get around the issue.

**Comment by jontowles** [comment] 2019-03-27 20:15
Can you provide a process for just manually installing the module so we can fix this?

**Comment by KoenZomers** [comment] 2019-03-27 20:18
I also am having customers where this is causing the release pipelines to fail. Hope this will be addressed with top priority.

**Comment by MajorSho** [comment] 2019-03-27 20:25
This has been a issue for near 24 hours now soo.... 
Broke our nightly deploys last night and has been not working all day (Being in the UK)

Just looking into alternatives but no way to test currently (it being 8:30pm here now) however it looks (not sure as can't confirm) 
that changing/adding a extra package source to the powershellgallery.com feed may fix the issue (can't confirm it though)

See what's listed there currently using get-packagesource in ps. 
Then add powershellgallery.com/api/v2/ as a 2nd failover feed and it may work....

packagemanagement/set-packagesource?view=powershell-6

I have no way of testing this till the morning currently but if someone wanted to test this theory and replies back it would be appreciated.

**Comment by edyoung** [comment] 2019-03-27 20:28
I believe this is resolved now - please let me know if you still see issues. Will follow up later with more info

**Comment by edyoung** [comment] 2019-03-27 23:18
Background to this incident.

oneget.org is a tiny web service (implementation at https://github.com/OneGet/website/ ) which just redirects certain web requests to the real resources which handle them. It is not required for most package management or PowerShellGet operations, but **is** used when searching for & installing new package providers or when bootstrapping nuget.exe when it is not present already.

Overnight, it entered a partially failed state, where one of the instances was failing requests with 503 and the other was responding slowly. This didn't correspond to any change our team made and I don't yet fully understand why it broke. I hope to discover more clues later. The site was recovered by scaling it up, which caused Azure to reset the instances. 

The incident took too long to resolve for several reasons:

1) The oneget redirections were not properly monitored by App Insights web tests, so we were not automatically informed of the issue when it started, and didn't realize until this incident was opened and we got to Pacific Time business hours. I have now updated the web tests to also check availability of oneget.org, which means we will be informed automatically.

2) Once investigation started, it took too long because I wasn't familiar enough with how this part of the site worked, partly because there hasn't been any change or required maintenance since 2016. This meant some wasted time identifying the cause of the issue and gaining access to the subscription hosting the web service.  I'm updating the team documentation to make the steps clearer should this issue recur.

Sorry for the extended outage.

**Comment by StefanScherer** [comment] 2019-03-30 18:43
There is again a problem with oneget.org

My current Packer builds on Azure want to install some PowerShell modules and therefore I have to 
```
    azure-arm: Installing AzureRM
    azure-arm: WARNING: Unable to download from URI 'https://oneget.org/nugetv2.feed.swidtag' to ''.
    azure-arm: WARNING: Unable to download from URI 'https://oneget.org/nuget-2.8.5.208.package.swidtag' to ''.
    azure-arm: WARNING: Unable to download from URI 'https://oneget.org/nuget-2.8.5.207.package.swidtag' to ''.
    azure-arm: WARNING: Unable to download from URI 'https://oneget.org/nuget-2.8.5.206.package.swidtag' to ''.
    azure-arm: WARNING: Unable to download from URI 'https://oneget.org/nuget-2.8.5.205.package.swidtag' to ''.
    azure-arm: WARNING: Unable to download from URI 'https://oneget.org/nuget-2.8.5.204.package.swidtag' to ''.
    azure-arm: WARNING: Unable to download from URI 'https://oneget.org/nuget-2.8.5.202.package.swidtag' to ''.
    azure-arm: WARNING: Unable to download from URI 'https://oneget.org/nuget-2.8.5.201.package.swidtag' to ''.
    azure-arm: WARNING: Unable to download from URI 'https://oneget.org/nuget-2.8.5.127.package.swidtag' to ''.
    azure-arm: WARNING: Unable to download from URI 'https://oneget.org/nuget-2.8.5.122.package.swidtag' to ''.
    azure-arm: WARNING: Unable to download from URI 'https://oneget.org/nuget-2.8.5.101.package.swidtag' to ''.
    azure-arm: WARNING: Unable to download from URI 'https://oneget.org/nuget-2.8.5.24.package.swidtag' to ''.
    azure-arm: WARNING: Unable to download from URI 'https://oneget.org/psl.feed.swidtag' to ''.
```

I manually curl'ed one of these urls:

```
$ curl -v https://oneget.org/nugetv2.feed.swidtag
*   Trying 40.112.143.134...
* TCP_NODELAY set
* Connected to oneget.org (40.112.143.134) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to oneget.org:443 
* stopped the pause stream!
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to oneget.org:443 
~
$ curl -v https://oneget.org/nugetv2.feed.swidtag
*   Trying 40.112.143.134...
* TCP_NODELAY set
* Connected to oneget.org (40.112.143.134) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=oneget.org
*  start date: Dec 11 18:13:30 2017 GMT
*  expire date: Dec 11 18:13:30 2019 GMT
*  subjectAltName: host "oneget.org" matched cert's "oneget.org"
*  issuer: C=US; ST=Washington; L=Redmond; O=Microsoft Corporation; OU=Microsoft IT; CN=Microsoft IT TLS CA 5
*  SSL certificate verify ok.
> GET /nugetv2.feed.swidtag HTTP/1.1
> Host: oneget.org
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
< Content-Type: text/html
< Server: Microsoft-IIS/10.0
< Date: Sat, 30 Mar 2019 18:36:13 GMT
< Content-Length: 27
< 
* Connection #0 to host oneget.org left intact
The service is unavailable.
```

This is my provision script to install a PowerShell module and to first install the package provider which causes me the trouble.

```powershell
$ProgressPreference = 'SilentlyContinue'
$ErrorActionPreference = 'Stop'

Write-Output "Installing AzureRM"
if (!(Get-PackageProvider -Name NuGet)) {
  Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
}
Install-Module -Name AzureRM -Verbose -Force
```

**Comment by edyoung** [comment] 2019-03-30 19:21
Telemetry from the service which does oneget.org redirection indicates it is working most of the time but failing some requests. I'm looking into it.

**Comment by edyoung** [comment] 2019-03-30 22:36
I have tried all the troubleshooting options I can find right now, and have a ticket open with internal Azure support to diagnose the issue. Also pursuing moving the service to Azure Functions, but that will take a little longer. Current state, as above, is that most requests work most of the time, but I see period (such as 12:00 - 13:00 UTC today) where most requests fail. 

As a partial workaround, note that Install-Module doesn't depend on oneget.org. If it's possible to have the package provider set up ahead of time and not reinstall/update it as part of the regular CI flow, you shouldn't see an issue.

**Comment by edyoung** [comment] 2019-04-02 21:24
An update on this - the service is now stable, but there is a background level of approx 1% of requests failing. We have a plan to remove 99-100% of the load on oneget.org but it will involve contacting a new fqdn. Please see issue #439 referenced above for more detail. Leaving this open for now for easier reference.

**Comment by Dave3of5** [comment] 2019-04-03 14:52
@edyoung Maybe just a thought but in terms of a mitigation it would be great if the build agents from Azure DevOps already had nuget preinstalled and didn't require it to be installed as part of the build process. I suspect a lot of you traffic is coming from those build agents constantly reinstalling NuGet.

**Comment by KoenZomers** [comment] 2019-04-03 14:57
> @edyoung Maybe just a thought but in terms of a mitigation it would be great if the build agents from Azure DevOps already had nuget preinstalled and didn't require it to be installed as part of the build process. I suspect a lot of the traffic is coming from those build agents constantly reinstalling NuGet.

They actually do already. Choose the "Hosted VS2017" build agent type and you can skip this step. If you choose the "Hosted" agent type, you are basically using a VS2015 instance and this does still require the manual installation of NuGet as a Package Manager.

**Comment by edyoung** [comment] 2019-04-03 22:54
We have now cut over the links which package management uses to bootstrap to a different CDN (see #439 for more detail). Please let us know of any problems you encounter, preferably via issue #439

**Comment by Dave3of5** [comment] 2019-04-04 07:17
> > @edyoung Maybe just a thought but in terms of a mitigation it would be great if the build agents from Azure DevOps already had nuget preinstalled and didn't require it to be installed as part of the build process. I suspect a lot of the traffic is coming from those build agents constantly reinstalling NuGet.
> 
> They actually do already. Choose the "Hosted VS2017" build agent type and you can skip this step. If you choose the "Hosted" agent type, you are basically using a VS2015 instance and this does still require the manual installation of NuGet as a Package Manager.

Sorry I should have said that it should be pre-installed on on the hosted rather than Hosted VS2017 sorry I wasn't clearer. I think in general though it should be pre-installed on all the hosted instances.

**Comment by edyoung** [comment] 2019-04-07 15:50
I'm not seeing any more issues in this area, so closing. @Dave3of5 I think that's a good idea. I will see if I can track down the right people. You might also want to create an issue at https://developercommunity.visualstudio.com/spaces/21/index.html

**Closed by edyoung** 2019-04-07 15:50 UTC
