### ISSUE TITLE
Package Provider for Zero Install

### ISSUE THREAD

**Issue by bastianeicher** [OneGet/oneget#206] opened 2016-08-31 07:34 UTC
[Zero Install](https://0install.de/) is a decentralized cross-platform software-installation system. Users can get Zero Install by downloading the [Boostrapper](https://0install.de/files/zero-install.exe). This will download and run a portable version of Zero Install and offer to permanently deploy it to the system.

This Bootstrapper can also act as a DLL containing a OneGet Package Provider. On first use this provider will download and deploy Zero Install, which contains the actual Package Provider for Zero Install.
(We discusses this previously [here](https://github.com/OneGet/oneget/issues/77#issuecomment-145854528).)

Provider Submission Form for the Zero Install Package Provider:
- Provider name: `0install`
- Description of the provider: Exposes Zero Install features such as feed search and desktop integration (install and uninstall) to OneGet.
- Provider packaging: A DLL installed together with Zero Install, registered in `HKCU|HKLM\Software\Microsoft\PackageManagement`
- Platform: all NT-based Windows versions
- Implemented OneGet APIs: `AddPackageSource`, `RemovePackageSource`, `ResolvePackageSources`, `FindPackage`, `FindPackageByFile`, `FindPackageByUri`, `GetInstalledPackages`, `DownloadPackage`, `InstallPackage`, `UninstallPackage`, `GetPackageDetails`
- Parameters specific to this provider:
  - `-Refresh`: Download the most recent metadata instead of using the local cache.
  - `-AllVersions`: List all available versions of a package instead of just the latest one.
  - `-GlobalSearch`: Use global feed mirror to search for packages instead of just registered package sources.
  - `-DeferDownload`: Perform desktop integration for the package but defer the download of the actual implementation until first use.
  - `-Scope CurrentUser|AllUsers`: Control whether packages are installed only for the current user (default) or for all users on the machine.
- Security model 
  - Zero Install itself is downloaded via HTTPS.
  - Zero Install itself has an AuthentiCode signature.
  - All feeds/packages are signed using GPG.
  - Key information server for GPG signatures is accessed via HTTPS.
  - Hashes of all downloaded implementations are checked against hashes specified in feeds.
- Licensing: GNU Lesser General Public License v3.0
- Package Source, i.e. repository: http://0install.de/catalog/ + user-specified
- Source code: https://github.com/0install/0install-win

**Comment by jianyunt** [comment] 2016-09-02 17:34
@bastianeicher,  I think there are two ways to allow users to find and install OneGet providers: 

1) PowerShell modules with tags: 'Provider' and 'PackageManagement'; 
2) we can create a [swidtag feed](https://github.com/OneGet/ProviderRegistry) and link to your host site with htpps for 0install provider.  Currently we need a single .dll or .exe (recommend .dll) containing all OneGet API implementation.

Choice 1) is certainly preferable.
 
For 2), OneGet only download the binaries and put them under  $env:ProgramFiles\PackageManagement\ProviderAssemblies or $env:localappdata\PackageManagement\ProviderAssemblies 

It does not run post install or custom actions.

I have a couple of questions:
1) what's the binary name of the 0install? it is needed in swidtag.
2) after the binary gets installed under ProviderAssemblies, there is no post installation action needed, correct? 
3) On your machine, can you copy your 0install binary under $env:ProgramFiles\PackageManagement\ProviderAssemblies,  re-launch PowerShell, Get-PackageProvider, can you see the 0install provider is loaded?
4) Following 3), can you do find-package, install-package, etc.  to make sure it works properly?
5) If the provider is not targeting Nano server, you may add some logic in the code so a user can know it is not work on Nano server. See [NuGet provider](https://github.com/OneGet/NuGetProvider) how to handle that.
6) what Windows OSs supported by the provider? WIn10, Win8...

Thank you for writing up the provider.

**Comment by bastianeicher** [comment] 2016-09-03 22:34
I think we will have to go with the swidtag feed route since my provider is written purely in C#.

Regarding your questions:
1) The binary is named `zero-install.exe` and can be downloaded here: https://0install.de/files/zero-install.exe
2) Once this binary is placed in `ProviderAssemblies` it does require an additional post installation action, however it performs this by itself when it is used for the first time.
3) and 4) Tested this and everything seems to work fine.
5) The provider does not (yet) support Nano Server. I did not find anything relating to this in the NuGet provider source. Could you point me to a specific file?
6) The provider supports Win7, 8, 8.1, 10, Server 2008 R2, Server 2012 and Server 2012 R2.

**Comment by jianyunt** [comment] 2016-09-06 17:34
Thanks for your response. Regarding Nano server, NuGet provider uses if CoreClr ... I suggest you may do something equivalent to check the platform and provide proper message.

**Comment by bastianeicher** [comment] 2016-09-08 23:11
Thanks for the CoreClr info. I'll add a check in the next release.

Are there any further steps required before creating a swidtag feed for the Zero Install provider?

**Comment by bastianeicher** [comment] 2016-09-18 15:46
I have created a swidtag feed for Zero Install that will be automatically updated with new releases:
https://0install.de/feeds/ZeroInstall.swidtag

Can you add a link to this feed to the OneGet Providers master list?

Can you add this feed to the

**Comment by jianyunt** [comment] 2016-09-22 16:50
@bastianeicher, I am tied up with oneget .netcore build right now. I will get back to you  in a couple of weeks to assist you to publish Zero Install. thank you for your patience.

**Comment by jianyunt** [comment] 2016-10-06 22:54
@bastianeicher Do you have instructions for users to  use the provider?  I tried:

PS C:\> find-package -provider 0install
WARNING: Name missing
PS C:\> find-package -provider 0install  -Name *
PS C:\> find-package -provider 0install  -Name * -verbose
VERBOSE: Using the provider '0install' for searching packages.
VERBOSE: Searching for short-name match in Catalog: *
VERBOSE: Searching for partial match in Catalog: *
VERBOSE: No package found matching '*'.

**Comment by bastianeicher** [comment] 2016-10-07 00:01
@jianyunt: Thanks for testing this.

There was a bug in 2.11.9 that caused the `-Name` parameter to be treated as required instead of optional. Only calls with specific package names like `Find-Package -Provider 0install -Name vlc` worked.

I have justed published 2.11.10 that fixes this. `Find-Package -Provider 0install` now lists all known packages in the registered packages sources.

**Comment by jianyunt** [comment] 2016-10-07 00:48
I can see find-package returns some results. But if I run find-package again returns nothing. See

PS C:\WINDOWS\system32> find-package -ProviderName 0install

Name                           Version          Source           Summary
----                           -------          ------           -------
Apache Ant                     1.9.4            http://0insta... A software project management and comprehension tool
Apache Maven                   3.3.3            http://0insta... A software project management and comprehension tool
aria2                          1.19.3           http://0insta... A lightweight multi-protocol and multi-source download utility
Audacity                       2.0.6            http://0insta... fast multi-track audio editor and recorder
Avidemux                       2.6.0            http://0insta... free video editor designed for simple cutting, filtering and encoding tasks
Blender                        2.76             http://0insta... versatile 3D animation creation suite
BlueScreenView                 1.52             http://0insta... scans minidump files created during 'blue screen of death' crashes
Boo                            0.9.4.9          http://0insta... object-oriented, statically typed, general-purpose programming language
CDBurnerXP                     4.5.5.5571       http://0insta... Free CD burner
Celestia                       1.6.1            http://0insta... free space simulation
Clementine                     1.0.1            http://0insta... A multiplatform music player
CMake                          3.2.0-pre2       http://0insta... cross platform make
cURL                           7.48.0           http://0insta... command line tool for transfering data specified with URL
DC++                           0.843            http://0insta... client for the ADC file sharing protocol
Database Design Tool           1.5              http://0insta... database schema diagramming tool
DocFetcher                     1.1.14           http://0insta... desktop search application
Dolphin                        4.0.2            http://0insta... a Gamecube and Wii emulator
DOSBox                         0.74             http://0insta... DOS Emulator
JetBrains dotPeek              1.1.1.33         http://0insta... free .NET Decompiler and Assembly Browser
Doxygen                        1.8.10           http://0insta... generate documentation from source code
DVDStyler                      2.7.1            http://0insta... cross-platform free DVD authoring application
Eclipse IDE for C/C++ Devel... 4.5              http://0insta... A multi-language software development environment - subset for C/C++
Eclipse IDE for Java Develo... 4.5              http://0insta... A multi-language software development environment - subset for Java
Eclipse for PHP Developers     4.5              http://0insta... A multi-language software development environment - subset for PHP
Eclipse IDE for Java EE Dev... 4.5              http://0insta... A multi-language software development environment - subset for Java EE
FileZilla                      3.16.1           http://0insta... cross-platform FTP, FTPS and SFTP client
FixParts                       0.8.10           http://0insta... text-mode tool designed to correct some common problems with computer partition tables
FLV Extract                    1.6.3            http://0insta... extracts video and audio from FLV files without decompressing or recompressing
WARNING: Can't find all required implementations:
 - http://0install.de/feeds/Frogatto.xml -> (problem)
     Rejected candidates:
       sha1new=c3f67f8310f010b9708ab861b1a2312b3ccdf178 (1.1.1): No run command
flvstreamer                    2.1.1.1          http://0insta... A command-line RTMP client intended to stream audio or video content.
Frogatto                                        http://0insta... A jump-and-run video game with a frog.
GCFScape                       1.8.5            http://0insta... Valve GCF file extractor
GPT fdisk                      0.8.10           http://0insta... text-mode tool designed to correct some common problems with computer partition tables
GIMP                           2.8.10           http://0insta... image retouching and editing tool
GitExtensions                  2.48.5           http://0insta... GitExtensions is a graphical interface for Git
Git for Windows                2.8.3            http://0insta... decentralized version control system
GnuPG                          1.4.11           http://0insta... GNU privacy guard - a free PGP replacement
gnuplot                        5.0.0            http://0insta... famous scientific plotting package
Golly                          2.6              http://0insta... Game of Life simulator
Gow                            0.8.0            http://0insta... the lightweight alternative to Cygwin
Gradle                         2.4              http://0insta... A software project management and comprehension tool
GraphCalc                      4.0.1            http://0insta... the ultimate Windows Graphing Calculator
HDGraph                        1.4.2.0          http://0insta... pie charts of disk space usage
IconsExtract                   1.47             http://0insta... Extracts ICOs from EXE, DLL, OCX, CPL, and in other file types.
Inkscape                       0.48.1-2         http://0insta... SVG graphics editor
IronPython                     2.7.3            http://0insta... implementation of Python running under .NET/Mono
Jitsi                          2.8.5426         http://0insta... VoIP and instant messaging
KeePass Classic                1.31             http://0insta... free open source password manager
KeePass Professional           2.34             http://0insta... free open source password manager
LibreOffice                    4.4.5.1          http://0insta... a free office suite
Lynx                           2.8.2-1          http://0insta... text-based web browser
MediathekView                  11               http://0insta... Mediatheksammlung der öffentlich-rechtlichen Sender.
Mozilla Firefox                44.0.2           http://0insta... free webbrowser of the Mozilla project
MP4Box                         0.4.6-2735       http://0insta... a MP4 multiplexer
Media Player Classic Home C... 1.7.10           http://0insta... free audio and video player for Windows
NAnt                           0.91-pre2        http://0insta... free .NET build tool
NetBeans All with Scala        1                http://0insta... A multi-language software development environment
NetBeans All                   8.1              http://0insta... A multi-language software development environment
NetBeans C/C++                 8.1              http://0insta... A multi-language software development environment - subset for C/C++
NetBeans Java EE               8.1              http://0insta... A multi-language software development environment - subset for Java (SE and EE)
NetBeans Java SE               8.1              http://0insta... A multi-language software development environment - subset for Java SE
NetBeans PHP                   8.1              http://0insta... A multi-language software development environment - subset for PHP
Nmap                           6.47             http://0insta... utility for network discovery and security auditing
Notepad++                      6.9.2            http://0insta... free source code editor and Notepad replacement that supports several languages
Oracle JDK                     8.0.102          http://0insta... official Oracle Java Development Kit
PDF Split and Merge            2.2.4            http://0insta... split and merge PDF documents
Pidgin                         2.11.0           http://0insta... Free multi-protocol chat client
pngcrush                       1.7.85           http://0insta... optimizer for PNG files
PPSSPP                         1.0.1            http://0insta... PSP emulator
Prime95                        28.7             http://0insta... Free Mersenne Prime Search Software
PuTTY                          0.66             http://0insta... Telnet and SSH client
Python                         3.2.5.1          http://0insta... portable Python for Windows
Scala                          2.11.4           http://0insta... functional and object-oriented programming language
ScummVM                        1.7.0            http://0insta... cross-platform interpreter for several point-and-click adventure engines
7-Zip Command-line             9.20             http://0insta... file archiver with a high compression ratio
7-Zip                          9.20             http://0insta... file archiver with a high compression ratio
Sublime Text                   2.0.2            http://0insta... a sophisticated text editor for code, markup and prose
TightVNC                       1.3.10           http://0insta... free remote-desktop tool
UltraVNC                       1.0.9.6.1        http://0insta... remote-desktop support software
VirtualDub                     1.10.4           http://0insta... video capture/processing utility for Windows platforms
VLC media player               2.2.4            http://0insta... powerful media player, playing most of the media codecs and video formats out there
WinMerge                       2.14.0           http://0insta... differencing and merging tool for Windows
WinSCP                         5.7              http://0insta... SFTP and FTP client for Windows
XZ Utils                       5.0.5            http://0insta... xz data compression tool for .xz and .lzma files
yEd Graph Editor               3.14.4           http://0insta... quickly and effectively generate high-quality diagrams
Zenmap                         6.47             http://0insta... Nmap frontend and results viewer
Zero Install Publishing Tools  2.11.9           http://0insta... helps you create and update Zero Install feeds


PS C:\WINDOWS\system32> find-package -ProviderName 0install
PS C:\WINDOWS\system32> get-package -ProviderName 0install
PS C:\WINDOWS\system32> install-package -ProviderName 0install  -name PuTTY
install-package : No match was found for the specified search criteria and package name 'PuTTY'. Try Get-PackageSource to see all available registered package
sources.
At line:1 char:1
+ install-package -ProviderName 0install  -name PuTTY
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by jianyunt** [comment] 2016-10-07 00:54
@bastianeicher,  FYI..
find-package -- a provider is expected to search packages in the source where a user registered or specified from cmdlet. No packages should be installed at this point of time.

get-package  -- a provider searches any installed packages on local machine.
install-package -- a particular package that a user requests will be installed from the source where a user provides.
uninstall-package -- installs a particular package.
...

**Comment by bastianeicher** [comment] 2016-10-07 01:13
Multiple calls to `Find-Package -ProviderName 0install` work fine for me. `Get-Package`, `Install-Package` and `Uninstall-Package` are implemented as you described.

Perhaps you updated the bootstrapper assembly in `%localappdata%\PackageManagement\ProviderAssemblies` but not the actual Zero Install deployment?
The Zero Install Provider will perform update-checks for this once a week but you can trigger an immediate update using `0install self-update`.

**Comment by jianyunt** [comment] 2016-10-07 01:45
I created feed and swidtag for 0install. You can see [here](https://github.com/OneGet/ProviderRegistry/blob/testing/zeroinstall.feed.swidtag)

Please try out by following steps:
$env:BootstrapProviderTestfeedUrl = "https://raw.githubusercontent.com/OneGet/ProviderRegistry/testing/zeroinstall.feed.swidtag"
find-packageprovider
install-packageprovider 0install -debug -verbose
find-package -provider 0install
find-package -provider 0install
get-package -provider 0install

**Comment by bastianeicher** [comment] 2016-10-07 10:49
Thanks. After some more debugging I found another potential issue that might cause `Find-Package` to fail after the first use. I will publish a new release with a fix later today.

Will the final swidtag feed file be hosted by Microsoft or can I host it on my own website? If it needs to be hosted Microsoft, what is the process for releasing updates?

When I create a new release the bootstrapper file on my server (https://0install.de/files/zero-install.exe) is simply replaced, invalidating the sha512 hash in the swidtag feed. The bootstrapper then loads the actual Zero Install implementation from a versioned archive (e.g., https://0install.de/files/hosted/ZeroInstall-2.11.10.tar.gz).

**Comment by jianyunt** [comment] 2016-10-07 17:14
@bastianeicher  you can host your swidtag. A user just need to set the path
$env:BootstrapProviderTestfeedUrl = "https://myfeed before using it.   I think that’s possibly much easier for you. 

 Here are something I recommend you to do to help the broader adoption of the 0install provider:

1. Add some tests such as find-package, install-package, get-package, uninstall-package.
2. In your 0install repo, make these tests running using appveryor so that everyone can see the current state of the 0install.
3. Document the 0install usage so that others can easily follow
4. I noticed when I do find-package, some software gets installed under C:\Program Files\Zero Install.  In general, find-package should not install everything to user's computer. If you have to, you need to prompt user for approval. 
5. I also noticed find-package changes my system Path. Normally providers do not do that because users do not like to change their path silently. If you have to, prompt user for approval.

The update process is manual. If you want to have fast update, I recommend you can wrap around it with PowerShell and publish it to the PowerShellGallery.com  just like I did for PackageManagement module.

Regarding to the hash, every time when you release a new version, the hash needs to be updated. For example, I use the following code to get the hash:

$filePath = "E:\test\test.dll"
$ha = [System.Security.Cryptography.SHA512]::Create()
$fs = [System.IO.File]::OpenRead($filePath)
[System.Convert]::ToBase64String($ha.ComputeHash($fs)).

**Comment by bastianeicher** [comment] 2016-10-07 18:55
When "installing" a package Zero Install creates shortcuts pointing to `0install.exe package_uri` instead of the application itself. This is similar to Windows Installer Advertised Shortcuts and supports features such as download-on-first use, self-healing, side-by-side versioning and background updates. This means that Zero Install itself needs to be located in a well-known location (e.g. `%AppData%` or `%ProgramFiles%`) before the Zero Install OneGet provider can install packages.



I would like to host my own swidtag feed so I can easily publish updates, but have it linked to from the public bootstrap feed so new users can easily discover it.

I have continuous integration for Zero Install set up here: https://0install.de/teamcity/

**Comment by bastianeicher** [comment] 2016-10-07 19:05
When a user downloads and runs https://0install.de/files/zero-install.exe they can chooses to deploy/install Zero Install to their computer. This also includes the OneGet provider (`ZeroInstall.OneGet.dll`), which is registered using the `SOFTWARE\PackageManagement` registry key.

The most straight-forward way to support `Install-PackageProvider 0install` would be to download and execute `zero-install.exe` to get a full install of Zero Install including the provider in a well-known location.

However, since bootstrapped OneGet providers must be single assemblies rather than actual installers, `zero-install.exe` also implements the OneGet provider interface. The first time it is accessed in any way it triggers the installation of Zero Install and then proxies all further requests to the real Zero Install OneGet provider.

This is why calls like `Find-Package` had side effects. I think this should be OK, since the user was asked and agreed to installing the 0install provider first. This is simply some additional work the provider needs to do on first use in order to get ready.

**Comment by bastianeicher** [comment] 2016-10-07 19:54
**Sample scenario**

User on a fresh Windows 10 machine enters:
```
Install-Package vlc -Provider 0install
```

OneGet finds no installed `0install` provider, downloads [providers.masterList.feed.swidtag](https://github.com/OneGet/ProviderRegistry/blob/master/providers.masterList.feed.swidtag), finds and follows link to https://0install.de/feeds/ZeroInstall.swidtag.

Prompt appears:
```
The provider '0install' is not installed.
Would you like PackageManagement to automatically download and install '0install' now?
```
User presses `Y`.

`zero-install.exe` is downloaded and placed in `%localappdata%\PackageManagement\ProviderAssemblies` and then loaded as a OneGet assembly.

`zero-install.exe` looks for an existing Zero Install deployment on the machine but finds none. `ZeroInstall-X.Y.Z.tar.gz` is downloaded and extracted to `%appdata%\Programs\Zero Install` or `%ProgramFiles%\Zero Install`.

`zero-install.exe` forwards the `Install-Package` call to `...\Zero Install\ZeroInstall.OneGet.dll`.

`ZeroInstall.OneGet.dll` downloads and extracts VLC and creates a start menu shortcut pointing to `...\Zero Install\0install.exe run http://0install.de/feeds/VLC.xml`.

When the user clicks the VLC shortcut Zero Install makes sure all required files are present, checks for updates in the background and runs VLC.

**Comment by bastianeicher** [comment] 2016-10-07 21:33
I have updated my swidtag feed and successfully tested this:
```
$env:BootstrapProviderTestfeedUrl = "https://0install.de/feeds/ZeroInstall.swidtag"
Install-Package vlc -Provider 0install
```

**Comment by jianyunt** [comment] 2016-10-12 17:45
@bastianeicher if you would like to host the swidtag feed, then in your 0Install source repo readme.md, you may want to document it how to use it. For example a user has to set 
         $env:BootstrapProviderTestfeedUrl = "https://0install.de/feeds/ZeroInstall.swidtag"
Is this the approach you want?

If you want to discover the provider via find-packageprovider, we have to put it in our Azure storage(The one I add in [github](https://raw.githubusercontent.com/OneGet/ProviderRegistry/testing/zeroinstall.feed.swidtag) is for testing purpose).  The problem is when you need to update the 0installer provider, you have to request us to update the swidtag in our storage. It may not be ideal for you.  The following approaches seem to be more convenient for you:
1.  $env:BootstrapProviderTestfeedUrl
2.  Add 0install.psm1 and import the 0install.exe in the .psm1 just as we did for PackageManangement module in PowerShellGallery.com.

**Comment by bastianeicher** [comment] 2016-10-15 08:57
@jianyunt thanks for the feedback.

The `$env:BootstrapProviderTestfeedUrl` approach is very helpful for local testing but not really useful for distribution to end-users, since they could simply download `zero-install.exe` themselves if they already need to know a specific URL.

Is there some sample code on how to create a PowerShell-based package provider that can be discovered by `Find-PackageProvider`?

Having my provider in your Azure storage and manually requesting updates is also OK for me, since I can still update Zero Install itself without having to change the provider very often.

I have improved the provider bootstrapping logic, so that changes to `PATH` only happen on `Install-Package` and an additional confirmation is requested from the user. I tried using `Request.AskPermission()` for this but this seemed to do nothing and always returned `true`. So I am using `Console.WriteLine()` and `Console.ReadLine()` instead. This does not seem to be the perfect solution though. Any suggestions?

**Comment by jianyunt** [comment] 2016-10-16 01:19
If you want to prompt users, you can use Request.ShouldContinue(). It's handy. See example in [PSL provider line 255] (https://github.com/OneGet/PSLProvider/blob/master/PackageList/PackageListProvider.cs).

If you want to wrap it with PowerShell, you need to create a psd1. For example,

New-ModuleManifest -Path c:\test\0install.psd1   to create the file, open the file, fill in the fields.

In the PrivateData section,  you need to add the following line.

Tags = @("PackageManagement","Provider")

"PackageManagementProviders" = '0install.dll'

As an example, you can take look at [myalbum.psd1](https://www.powershellgallery.com/packages/MyAlbum/0.1.2/Content/MyAlbum.psd1)
I looked the [code here](https://github.com/OneGet/oneget/blob/master/src/Microsoft.PackageManagement.MetaProvider.PowerShell/PowerShellMetaProvider.cs),  we only support .dll. This dll implements the OneGet provider class. It will be loaded while import-packageprovider or install-packageprovider. Thus it looks like you need to change your 0install.exe to 0install.dll. I hope it's ok with you.

In your case, you will have 0install.dll and 0install.psd1. That's it.

**Comment by bastianeicher** [comment] 2016-10-16 09:35
`.ShouldContinue()` seems to be missing from [ProviderSdk:Request](https://github.com/OneGet/ProviderSdk/blob/master/Sdk/Request.cs). I've copied it from [PSLProvider:Request](https://github.com/OneGet/PSLProvider/blob/master/Sdk/Request.cs). Is the difference in available methods intentional?

Thanks for the PowerShell instructions. I will give it a try.

**Comment by jianyunt** [comment] 2016-10-17 16:52
Not intentional. It looks like  ProviderSdk needs to be updated.

**Comment by bastianeicher** [comment] 2016-10-20 22:23
I have successfully published a `0install` provider in the PowerShell gallery. The following works:
```
Install-PackageProvider 0install -Scope CurrentUser
Install-Package vlc -Provider 0install
```

However, there seem to be some disadvantages compared to the swidtag solution:
 * `Install-Package vlc -Provider 0install` does not automatically suggest installing the `0install` provider if it is missing. An explicit `Install-PackageProvider` call is required.
 * When I open a new PowerShell session the PowerShell gallery-based `0install` provider does not get loaded automatically. Calls like `Get-Package vlc` do not include results from the `0install` package provider, unless it is first loaded with `Import-PackageProvider 0install`.

**Comment by bastianeicher** [comment] 2016-10-20 22:27
I have published a versioned copy of the boostrapper (`zero-install.exe`) here:
http://0install.de/files/zero-install-2.12.0.exe
The hash of this file will not change when new releases are published.

Could you add this file to the official ProviderRegistry swidtag feed? It's no problem if future updates don't get added right away.

**Comment by jianyunt** [comment] 2016-10-20 23:47
It is expected users to run find-PackageProvider and Install-PackageProvider. I do not see our customers complaining about it.  For any providers in PowerShellGallery.com, it is needed to Install-PackageProvider.

After the install, a user can  do 'find-package vls -provider 0install', it will load the  0install provider. No import-pp is necessary.

**Comment by bastianeicher** [comment] 2016-10-24 17:53
If I use `Find-Package somepackage` without specifying a specific package provider I get results from all installed package providers. This seems to be the main advantage of OneGet to me: easily finding packages without always having to know the source in advance.

However, if I install a provider from PowerShell Gallery using `Install-PackageProvider` and then open a new PowerShell session this provider will not be included in `Find-Package somepackage` queries unless it is explicitly selected using `-Provider` or imported using `Import-PackageProvider`.

I understand that this is expected behavior. The behavior of providers installed to `%localappdata%\PackageManagement\ProviderAssemblies` just seems a lot more convenient. Is adding 0install to the ProviderRegistry swidtag feed still an option?

**Comment by jianyunt** [comment] 2016-11-03 22:53
I am glad to see 0intall module in the PowerShellGallery.com!

We would like more providers in the gallery instead of our internal storage. It's good for maintainers. In terms of user experiences, it's reasonable.  In addition, as you may noticed, we added the NuGet provider assembly in with PackageManagement module folder on [PowerShellCore](https://github.com/PowerShell/PowerShell). This means there won't be bootstrapping on Linux or Mac at least for now. Gallery is the way to go. thx @bastianeicher!

**Closed** 2017-01-17 18:53 UTC
